# Generated by Django 5.2.6 on 2025-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_ceo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='color',
            field=models.JSONField(blank=True, default=list, help_text='Список цветов в формате JSON, например: ["красный", "синий", "зеленый"]', null=True, verbose_name='Цвета'),
        ),
    ]
