# Generated by Django 5.2.6 on 2025-12-12 11:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_project_color_projecttranslation_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceo',
            options={'verbose_name': 'CEO', 'verbose_name_plural': '07. CEO'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': '08. Галереи'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Участник команды', 'verbose_name_plural': '06. Участники команды'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='project',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='height',
        ),
        migrations.RemoveField(
            model_name='project',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='width',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectseo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttranslation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='projectvideo',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидка')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='website.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Элемент проекта',
                'verbose_name_plural': 'Элементы проекта',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.projectitem', verbose_name='Элемент проекта'),
        ),
        migrations.AddField(
            model_name='projectseo',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='website.projectitem', verbose_name='Элемент проекта'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.projectitem', verbose_name='Элемент проекта'),
        ),
        migrations.CreateModel(
            name='ProjectItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('color', models.JSONField(blank=True, default=list, help_text='Список цветов в формате JSON, например: ["красный", "синий", "зеленый"]', null=True, verbose_name='Цвета')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.projectitem')),
            ],
            options={
                'verbose_name': 'Элемент проекта Translation',
                'db_table': 'website_projectitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
