# Generated by Django 5.2.6 on 2025-12-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_ceo_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': '10. Формы обратной связи',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': '09. Галереи'},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'verbose_name': 'Элемент проекта', 'verbose_name_plural': '03. Элементы проекта'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': '05. Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категория услуги', 'verbose_name_plural': '04. Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Участник команды', 'verbose_name_plural': '07. Участники команды'},
        ),
    ]
