# Generated by Django 5.2.6 on 2025-12-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_create_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectseo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='website.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.project', verbose_name='Проект'),
        ),
        # ProjectItem va ProjectItemTranslation allaqachon o'chirilgan, shuning uchun DeleteModel operatsiyalari o'chirildi
        # migrations.DeleteModel(
        #     name='ProjectItemTranslation',
        # ),
        # migrations.DeleteModel(
        #     name='ProjectItem',
        # ),
    ]
