# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_gallery_image_galleryimage'),
        ('website', '0010_remove_projectitem_project_and_more'),
    ]

    operations = [
    ]
