# Generated by Django 5.2.6 on 2025-12-18 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_0008_0010'),
    ]

    operations = [
        # project_item fieldlari allaqachon olib tashlangan, shuning uchun RemoveField operatsiyalari o'chirildi
        # migrations.RemoveField(
        #     model_name='projectitem',
        #     name='project',
        # ),
        # migrations.RemoveField(
        #     model_name='projectseo',
        #     name='project_item',
        # ),
        # migrations.RemoveField(
        #     model_name='projectimage',
        #     name='project_item',
        # ),
        # migrations.RemoveField(
        #     model_name='projectvideo',
        #     name='project_item',
        # ),
        # project fieldlari allaqachon qo'shilgan, shuning uchun AddField operatsiyalari o'chirildi
        # migrations.AddField(
        #     model_name='projectimage',
        #     name='project',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project', verbose_name='Проект'),
        # ),
        # migrations.AddField(
        #     model_name='projectseo',
        #     name='project',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='website.project', verbose_name='Проект'),
        # ),
        # migrations.AddField(
        #     model_name='projectvideo',
        #     name='project',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='website.project', verbose_name='Проект'),
        # ),
        # ProjectItem va ProjectItemTranslation allaqachon o'chirilgan, shuning uchun DeleteModel operatsiyalari o'chirildi
        # migrations.DeleteModel(
        #     name='ProjectItemTranslation',
        # ),
        # migrations.DeleteModel(
        #     name='ProjectItem',
        # ),
    ]
